remote_theme           : "mmistakes/minimal-mistakes"
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


minimal_mistakes_skin    : "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "pt-BR"
date_format              : "%d-%m-%Y"
title                    : "Oficina GitHub Pages"
title_separator          : "-"
subtitle                 : "Um treinamento para a utilização do GitHub Pages para hospedagem de sites" # site tagline that appears below site title in masthead
name                     : "Leandro Souza"
description              : "Treinamento GitHub Pages"
url                      : "https://leandro-costa.github.io/"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "leandro-costa/leandro-costa.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)




# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      toc: true
      toc_label: "Nesta página"
      toc_icon: "cog"
      toc_sticky: true
      sidebar:
        nav: "posts"

author:
  name: "Leandro Souza"
  avatar: "https://lh3.googleusercontent.com/-49UTXwCFuxU/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuclyGN2w2gMjjGuoi66-W35hhmIMZg/photo.jpg?sz=92"
  bio: "Professor EBTT." # Note: Markdown is allowed
  location: "IFBA SAJ"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leandro-souza"

